baseURL = "https://arbor-analytics.com/"
languageCode = "en-us"
#title = "Arbor Custom Analytics LLC"
theme = "minimal"
disqusShortname = "mbrussell" # delete this to disable disqus comments 
googleAnalytics = "UA-136790074-1"

[params]
    author = "Matt Russell" 
    description = "Arbor Custom Analytics LLC provides data and analytics consulting services for the forest products industry."
    githubUsername = "#"
    accent = "darkgreen"
    showBorder = true
    backgroundColor = "white"
    font = "Roboto" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "white"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    profilePic = "https://arbor-analytics.com/post/2019-07-14-using-google-forms-to-analyze-confidence-intervals-a-teaching-statistics-activity_files/arbor_horiz.png"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Blog"
    weight = 2

[[menu.main]]
    url = "/events/"
    name = "Events"
    weight = 3
    
[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:matt@arbor-analytics.com"
    name = "envelope-o"
    weight = 1
    
[[menu.icon]]
    url = "https://twitter.com/arbor_analytics"
    name = "twitter"
    weight = 2    

[[menu.icon]]
    url = "https://github.com/mbrussell/"
    name = "github"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/matthew-russell-70a94824/"
    name = "linkedin"
    weight = 4
    
[[menu.icon]]
    url = "https://scholar.google.com/citations?user=4OO83OcAAAAJ&hl=en&authuser=1"
    name = "fas fa-graduation-cap"
    weight = 5
