---
title: 'Imputing missing tree heights from a forest inventory'
author: Matt Russell
date: '2023-02-17'
slug: []
categories:
  - Analytics
tags:
  - analytics
  - forest measurements
  - forest inventory
  - regression
---

<script src="{{< blogdown/postref >}}index_files/kePrint/kePrint.js"></script>
<link href="{{< blogdown/postref >}}index_files/lightable/lightable.css" rel="stylesheet" />


<center>
<img src="sunrise%20through%20pines.jpg" width="400" />
</center>
<center>
<em>Eastern white pine trees at sunrise in Maine.</em>
</center>
<div id="section" class="section level2">
<h2></h2>
<p>Total height is one of the most useful measurements of a tree, but it’s often not measured. This is because measuring heights takes considerable time and effort. While it may be easy for a forester to measure the diameter of a tree, to obtain a proper measurement of a tree you generally need to walk away from it. This can take a lot of time if there are dozens of trees on a forest inventory plot.</p>
<p>To expedite the time spent in the field, most foresters will subsample tree heights. For example, foresters can measure the height of every fourth tree they encounter, or measure heights on all trees in every fourth inventory plot.</p>
<p>Forest inventory data are often used in a variety of applications after the data are collected. For example, data are used to determine stand volume, biomass, and carbon. However, most of the equations that determine those attributes require a value for the tree’s height. So what do you do when you didn’t collect heights on all trees?</p>
<p>This post will discuss the idea of imputation, or how to make the best prediction by using all data available. An example is shown in R using a few different approaches are used to impute tree heights based on traditional forest inventory measurements.</p>
</div>
<div id="penobscot-experimental-forest-data" class="section level2">
<h2>Penobscot Experimental Forest data</h2>
<p>The data used here is from the <a href="https://www.fs.usda.gov/rds/archive/catalog/RDS-2012-0008-2">Penobscot Experimental Forest (PEF)</a>, a long-term silvicultural experiment based in central Maine. The species are typical of the mixed-species Acadian Forest, an ecotone between the boreal forests to the north and the broadleaf forests to the south. Permanent sample plots are located in several management units (MU) across the forest.</p>
<p>There are several remeasurements of permanent sample plots on trees in the PEF database. I use only the most recent measurement from each plot for this analysis. On the PEF, permanent sample plots consist of nested 1/5-, 1/20-, and 1/50-acre circular plots for measuring trees &gt;= 4.5 inches, 2.5 to 4.4 inches, and 0.5 to 2.4 inches in diameter at breast height, respectively. Tree heights are measured on one-third of the plots. (NOTE: I skip some of the data cleaning on this data set in this post, but you can <a href="https://github.com/mbrussell/myblog/tree/master/content/post/2023-02-15-imputing-missing-tree-heights-from-a-forest-inventory">find the raw data and the full code set on GitHub</a>.)</p>
<p>In total there are 14,489 total trees in the database, but only 3,382 have height measurements. Here are 10 random rows of data, and note the missing heights for many of them:</p>
<pre class="r"><code>library(tidyverse)</code></pre>
<table class="table lightable-paper" style="margin-left: auto; margin-right: auto; font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
MU
</th>
<th style="text-align:right;">
Plot
</th>
<th style="text-align:right;">
Year
</th>
<th style="text-align:right;">
TreeNum
</th>
<th style="text-align:left;">
FVSspID
</th>
<th style="text-align:right;">
dbh
</th>
<th style="text-align:right;">
HT
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
20
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
2008
</td>
<td style="text-align:right;">
35100
</td>
<td style="text-align:left;">
RS
</td>
<td style="text-align:right;">
8.9
</td>
<td style="text-align:right;">
65.3
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
29B
</td>
<td style="text-align:right;">
34
</td>
<td style="text-align:right;">
2011
</td>
<td style="text-align:right;">
45600
</td>
<td style="text-align:left;">
BF
</td>
<td style="text-align:right;">
7.2
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
10
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
2010
</td>
<td style="text-align:right;">
30300
</td>
<td style="text-align:left;">
RM
</td>
<td style="text-align:right;">
6.4
</td>
<td style="text-align:right;">
43.8
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
12
</td>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
2014
</td>
<td style="text-align:right;">
94700
</td>
<td style="text-align:left;">
WC
</td>
<td style="text-align:right;">
7.0
</td>
<td style="text-align:right;">
16.0
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
4
</td>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
2009
</td>
<td style="text-align:right;">
82800
</td>
<td style="text-align:left;">
BF
</td>
<td style="text-align:right;">
6.5
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
21
</td>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
2013
</td>
<td style="text-align:right;">
5200
</td>
<td style="text-align:left;">
WC
</td>
<td style="text-align:right;">
6.9
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
23A
</td>
<td style="text-align:right;">
73
</td>
<td style="text-align:right;">
2001
</td>
<td style="text-align:right;">
15100
</td>
<td style="text-align:left;">
BF
</td>
<td style="text-align:right;">
5.6
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
24
</td>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
2005
</td>
<td style="text-align:right;">
64200
</td>
<td style="text-align:left;">
EH
</td>
<td style="text-align:right;">
8.1
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
22
</td>
<td style="text-align:right;">
31
</td>
<td style="text-align:right;">
2014
</td>
<td style="text-align:right;">
23800
</td>
<td style="text-align:left;">
BF
</td>
<td style="text-align:right;">
5.4
</td>
<td style="text-align:right;">
50.0
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
23A
</td>
<td style="text-align:right;">
62
</td>
<td style="text-align:right;">
2001
</td>
<td style="text-align:right;">
94300
</td>
<td style="text-align:left;">
EH
</td>
<td style="text-align:right;">
7.6
</td>
<td style="text-align:right;">
NA
</td>
</tr>
</tbody>
</table>
<p>We can plot the tree diameter-height relationship, and note the many species are found in the database. Data are stored in the <strong>tree</strong> data set, and the <code>dbh</code> and <code>HT</code> variables are of interest. Note the warning message that R provides–this is a result of the 11,000+ trees where height was not measured:</p>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre class="r"><code>ggplot(tree, aes(x = dbh, y = HT, col = FVSspID)) +
  geom_point() +
  labs (x = &quot;Tree diameter (inches)&quot;,
        y = &quot;Tree height (feet)&quot;)</code></pre>
<pre><code>## Warning: Removed 11108 rows containing missing values (geom_point).</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>One way to determine the heights of missing trees is to apply a regional equation that predicts total height. In the northeast region of the United States, the <a href="https://www.fs.usda.gov/fmsc/ftp/fvs/docs/overviews/FVSne_Overview.pdf">Forest Vegetation Simulator-Northeast variant</a> is a popular model for determining forest growth and yield. The FVS variant uses two model forms to determine height, depending on species. The first is the Curtis-Arney model form:</p>
<p><span class="math display">\[HT=4.5+a_0\text{ exp}(a_1 \times DBH^{a_2})\]</span>
and the second is the Wykoff model form:</p>
<p><span class="math display">\[HT=4.5+\text{ exp}(b_1 + b_2 / DBH+1)\]</span>
To apply these equations to the <strong>tree</strong> data set, the <code>FVSNE.SPP()</code> function specifies which species uses which height equation by specifying the <code>HTDBH_EQ</code> variable:</p>
<pre class="r"><code>FVSNE.SPP &lt;- function(SPP){
     if(SPP == &#39;BF&#39;){HTDBH_EQ = &#39;C&#39;; Dbw = 0.1}
else if(SPP == &#39;TA&#39;){HTDBH_EQ = &#39;C&#39;; Dbw = 0.1}
else if(SPP == &#39;WS&#39;){HTDBH_EQ = &#39;C&#39;; Dbw = 0.2}
else if(SPP == &#39;RS&#39;){HTDBH_EQ = &#39;C&#39;; Dbw = 0.2}
else if(SPP == &#39;RN&#39;){HTDBH_EQ = &#39;C&#39;; Dbw = 0.1}
else if(SPP == &#39;WP&#39;){HTDBH_EQ = &#39;C&#39;; Dbw = 0.4}
else if(SPP == &#39;WC&#39;){HTDBH_EQ = &#39;W&#39;; Dbw = 0.1}
else if(SPP == &#39;EH&#39;){HTDBH_EQ = &#39;C&#39;; Dbw = 0.1}
else if(SPP == &#39;RM&#39;){HTDBH_EQ = &#39;W&#39;; Dbw = 0.2}
else if(SPP == &#39;SM&#39;){HTDBH_EQ = &#39;W&#39;; Dbw = 0.2}
else if(SPP == &#39;YB&#39;){HTDBH_EQ = &#39;W&#39;; Dbw = 0.1}
else if(SPP == &#39;PB&#39;){HTDBH_EQ = &#39;W&#39;; Dbw = 0.1}
else if(SPP == &#39;GB&#39;){HTDBH_EQ = &#39;W&#39;; Dbw = 0.1}
else if(SPP == &#39;AB&#39;){HTDBH_EQ = &#39;W&#39;; Dbw = 0.1}
else if(SPP == &#39;WA&#39;){HTDBH_EQ = &#39;W&#39;; Dbw = 0.2}
else if(SPP == &#39;BA&#39;){HTDBH_EQ = &#39;W&#39;; Dbw = 0.2}
else if(SPP == &#39;QA&#39;){HTDBH_EQ = &#39;W&#39;; Dbw = 0.3}
else if(SPP == &#39;BP&#39;){HTDBH_EQ = &#39;W&#39;; Dbw = 0.2}
else if(SPP == &#39;BT&#39;){HTDBH_EQ = &#39;W&#39;; Dbw = 0.2}
else if(SPP == &#39;OK&#39;){HTDBH_EQ = &#39;W&#39;; Dbw = 0.2}
else if(SPP == &#39;EL&#39;){HTDBH_EQ = &#39;W&#39;; Dbw = 0.1}
else if(SPP == &#39;HH&#39;){HTDBH_EQ = &#39;W&#39;; Dbw = 0.2}
else{HTDBH_EQ = &#39;W&#39;; Dbw = 0.1}
  return(c(HTDBH_EQ = HTDBH_EQ, Dbw = Dbw))}</code></pre>
<p>The <code>FVSNE.HTDBH()</code> function adds the species-specific coefficients for each species:</p>
<pre class="r"><code>#FVS HT-DBH (Table 4.1.1 in FVS-NE guide)
FVSNE.HTDBH &lt;- function(SPP,HTDBH_EQ,DBH,Dbw){
     if(SPP==&#39;BF&#39;){ca_a1=2163.9468; ca_a2=6.2688; ca_a3=-0.2161; w_a1=4.5084; w_a2=-6.0116}     
else if(SPP==&#39;TA&#39;){ca_a1=2163.9468; ca_a2=6.2688; ca_a3=-0.2161; w_a1=4.5084; w_a2=-6.0116}     
else if(SPP==&#39;WS&#39;){ca_a1=2163.9468; ca_a2=6.2688; ca_a3=-0.2161; w_a1=4.5084; w_a2=-6.0116}     
else if(SPP==&#39;RS&#39;){ca_a1=2163.9468; ca_a2=6.2688; ca_a3=-0.2161; w_a1=4.5084; w_a2=-6.0116}     
else if(SPP==&#39;RN&#39;){ca_a1=266.4562; ca_a2=3.9931; ca_a3=-0.386; w_a1=4.5084; w_a2=-6.0116}     
else if(SPP==&#39;WP&#39;){ca_a1=2108.8442; ca_a2=5.6595; ca_a3=-0.1856; w_a1=4.609; w_a2=-6.1896}     
else if(SPP==&#39;WC&#39;){ca_a1=2163.9468; ca_a2=6.2688; ca_a3=-0.2161; w_a1=4.5084; w_a2=-6.0116}     
else if(SPP==&#39;EH&#39;){ca_a1=266.4562; ca_a2=3.9931; ca_a3=-0.386; w_a1=4.5084; w_a2=-6.0116}     
else if(SPP==&#39;RM&#39;){ca_a1=268.5564; ca_a2=3.1143; ca_a3=-0.2941; w_a1=4.3379; w_a2=-3.8214}     
else if(SPP==&#39;SM&#39;){ca_a1=209.8555; ca_a2=2.9528; ca_a3=-0.3679; w_a1=4.4834; w_a2=-4.5431}     
else if(SPP==&#39;YB&#39;){ca_a1=170.5253; ca_a2=2.6883; ca_a3=-0.4008; w_a1=4.4388; w_a2=-4.0872}    
else if(SPP==&#39;PB&#39;){ca_a1=170.5253; ca_a2=2.6883; ca_a3=-0.4008; w_a1=4.4388; w_a2=-4.0872}     
else if(SPP==&#39;GB&#39;){ca_a1=170.5253; ca_a2=2.6883; ca_a3=-0.4008; w_a1=4.4388; w_a2=-4.0872}     
else if(SPP==&#39;AB&#39;){ca_a1=526.1393; ca_a2=3.8923; ca_a3=-0.2259; w_a1=4.4772; w_a2=-4.7206}     
else if(SPP==&#39;WA&#39;){ca_a1=91.3528; ca_a2=6.9961; ca_a3=-1.2294; w_a1=4.5959; w_a2=-6.4497}     
else if(SPP==&#39;BA&#39;){ca_a1=178.9308; ca_a2=4.9286; ca_a3=-0.6378; w_a1=4.6155; w_a2=-6.2945}     
else if(SPP==&#39;QA&#39;){ca_a1=337.6685; ca_a2=3.6273; ca_a3=-0.3208; w_a1=4.5128; w_a2= -4.9918}     
else if(SPP==&#39;BP&#39;){ca_a1=91.3528; ca_a2=6.9961; ca_a3=-1.2294; w_a1=4.5959; w_a2= -6.4497}     
else if(SPP==&#39;BT&#39;){ca_a1=91.3528; ca_a2=6.9961; ca_a3=-1.2294; w_a1=4.5959; w_a2=-6.4497}     
else if(SPP==&#39;OK&#39;){ca_a1=196.0565; ca_a2=3.0067; ca_a3=-0.385; w_a1=4.5225; w_a2=-4.9401}     
else if(SPP==&#39;EL&#39;){ca_a1=1005.8067; ca_a2=4.6474; ca_a3=-0.2034; w_a1=4.3744; w_a2=-4.5257}     
else if(SPP==&#39;HH&#39;){ca_a1=109.7324; ca_a2=2.2503; ca_a3=-0.413; w_a1=4.0322; w_a2=-3.0833}     
else{ca_a1=68.5564; ca_a2=3.1143; ca_a3=-0.2941; w_a1=4.3379; w_a2=-3.8214}
    HT = ifelse(HTDBH_EQ ==&quot;C&quot; &amp; DBH &lt; 3.0,(4.5+ca_a1*exp(-1*ca_a2*3**ca_a3)-4.51*(DBH-Dbw)/(3-Dbw))+4.51,
          ifelse(HTDBH_EQ ==&quot;C&quot; &amp; DBH &gt;= 3.0,4.5+ca_a1*exp(-1*ca_a2*DBH**ca_a3),
            4.5+exp(w_a1+w_a2/(DBH+1))))
    return(HT=HT)}</code></pre>
<p>Now we predict the height of each tree in the PEF data using the FVS-NE equation:</p>
<pre class="r"><code>aa &lt;- sapply(tree$FVSspID, FVSNE.SPP)

tree &lt;- tree %&gt;% 
  mutate(HTDBH_EQ = t(aa)[,1],
         Dbw = as.numeric(t(aa)[,2]),
         HT_PRED_FVS = mapply(FVSNE.HTDBH, SPP = FVSspID, 
                     HTDBH_EQ = HTDBH_EQ, 
                     DBH = dbh, 
                     Dbw = Dbw))</code></pre>
<p>We can see the for the heights measured, the FVS-predicted heights show a bimodal distribution. This is likely a result of the two different equations used:</p>
<pre class="r"><code>ggplot(tree_ht, aes(x = height_feet, fill = Height_model)) +
  geom_density(alpha = 0.1) +
  labs (x = &quot;Height (feet)&quot;) +
  theme(panel.background = element_rect(fill = &quot;NA&quot;),
        axis.line = element_line(color=&quot;black&quot;),
        legend.title = element_blank(),
        legend.position = c(0.8, 0.8))</code></pre>
<pre><code>## Warning: Removed 11108 rows containing non-finite values (stat_density).</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
</div>
<div id="modeling-tree-height-with-a-mixed-model" class="section level2">
<h2>Modeling tree height with a mixed model</h2>
<p>We could use the FVS equations as predictions of tree height, but the drawback is that those equations are not localized to the PEF. The benefit is we have numerous predictions of tree height on the <em>same forest</em> that we want to predict on. And we should take advantage of that. Hence, we can use mixed models to make localized predictions.</p>
<p>For most models of tree height, nonlinear models work well. However, there is a general linear trend between height and diameter, so for the purpose of this tutorial, we’ll choose a linear model:</p>
<pre class="r"><code>p.ht &lt;- ggplot(tree, aes(x = dbh, y = HT)) +
  geom_point() +
  stat_smooth() +
  labs (x = &quot;Tree diameter (inches)&quot;,
        y = &quot;Tree height (feet)&quot;)
p.ht</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>A popular R package for performing linear mixed models is <strong>lme4</strong>. We will use it to fit a linear mixed model that specifies fixed and random effects:</p>
<pre class="r"><code>library(lme4)</code></pre>
<p>The <code>lmer()</code> function is the mixed model equivalent of <code>lm()</code> and parameter estimates are fit using maximum likelihood. We know that there are several plots nested within several management units from multiple species. So, we can specify these as random effects on the intercept, writing <code>+ (1 | FVSspID/MU/Plot)</code> after specifying the independent variable <code>DBH</code>:</p>
<pre class="r"><code>ht.lme &lt;- lmer(HT ~ dbh + (1 | FVSspID/MU/Plot),
             data = tree)
summary(ht.lme)</code></pre>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: HT ~ dbh + (1 | FVSspID/MU/Plot)
##    Data: tree
## 
## REML criterion at convergence: 22280.2
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -5.3634 -0.5141  0.0374  0.5428  4.5896 
## 
## Random effects:
##  Groups            Name        Variance Std.Dev.
##  Plot:(MU:FVSspID) (Intercept) 10.94    3.308   
##  MU:FVSspID        (Intercept) 32.66    5.715   
##  FVSspID           (Intercept) 52.84    7.269   
##  Residual                      34.65    5.886   
## Number of obs: 3381, groups:  
## Plot:(MU:FVSspID), 437; MU:FVSspID, 148; FVSspID, 18
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept) 23.94183    2.00369   11.95
## dbh          2.99752    0.04432   67.64
## 
## Correlation of Fixed Effects:
##     (Intr)
## dbh -0.171</code></pre>
<p>We can see from the <code>lmer()</code> output that the values for the fixed effects are 23.94183 and 2.99752, respectively. The <em>Random effects</em> section contains details on the variance of the random effects and their residuals. We could use the <code>ranef()</code> function to extract the values of the random effect terms. (But note there will be many values because there are many Species-MU-Plot combinations.)</p>
</div>
<div id="imputing-tree-height" class="section level2">
<h2>Imputing tree height</h2>
<p>Once we have a model, we can use R’s <code>predict()</code> function to apply it to our <code>tree</code> data set. We use the <code>re.form</code> statement to specify that we want to make predictions using fixed effects only, or predictions using subject-specific random effects (e.g., the best linear unbiased predictions).</p>
<p>If <code>re.form = NULL</code>, predictions are made including all random effects. This would be fitting if you subsampled tree heights measured on an individual plot. Adding the <code>allow.new.levels = TRUE</code> statement will make predictions using fixed effects only. This is ideal for the PEF data because there are many plots where no trees were measured for height:</p>
<pre class="r"><code>tree &lt;- tree %&gt;% 
   mutate(HT_PRED_MIXED = predict(ht.lme, tree, re.form = NULL, allow.new.levels = TRUE))</code></pre>
<p>When compared to the FVS model, we can see that the mixed model shows smaller residuals and less bias across the range in heights:</p>
<pre class="r"><code>p.ht.fvs &lt;- ggplot(tree, aes(x = HT_PRED_FVS, y = (HT-HT_PRED_FVS))) +
  geom_point() +
  stat_smooth(se = F) +
  scale_y_continuous(limits = c(-50, 30)) +
  labs(x = &#39;Predicted FVS-NE height (ft)&#39;,
       y = &#39;Bias (ft)&#39;,
       title = &quot;FVS-Northeast&quot;)

p.ht.mixed &lt;- ggplot(tree, aes(x = HT_PRED_MIXED, y = (HT-HT_PRED_MIXED))) +
  geom_point() +
  stat_smooth(se = F) +
  scale_y_continuous(limits = c(-50, 30)) +
  labs(x = &#39;Predicted random-effects height (ft)&#39;,
       y = &#39;Bias (ft)&#39;,
       title = &quot;Mixed model (fixed + random effects)&quot;)</code></pre>
<pre class="r"><code>library(patchwork)
p.ht.fvs + p.ht.mixed</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
</div>
<div id="conclusion" class="section level2">
<h2>Conclusion</h2>
<p>There are many ways to impute missing values, and mixed models are very fitting for forest inventory data because of their hierarchical structure. If variables of interest are subsampled, mixed models can account for random variation at different levels. R’s <code>predict()</code> function works excellent for making mixed model predictions at these different levels.</p>
<p>–</p>
<p><em>By Matt Russell. PS: I’ve suppressed some of the code that cleans the Penobscot data set. You can <a href="https://github.com/mbrussell/myblog/tree/master/content/post/2023-02-15-imputing-missing-tree-heights-from-a-forest-inventory">find the raw data and the full code set on GitHub</a>.</em></p>
</div>
